In [47]:
import numpy as np # used for handling numbers
import pandas as pd # used for handling the dataset
from sklearn.impute import SimpleImputer # used for handling missing data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder # used for encoding categorical data
from sklearn.model_selection import train_test_split # used for splitting training and testing data
from sklearn.preprocessing import StandardScaler # used for feature scaling
from sklearn.preprocessing import Normalizer # used for feature scaling

In [48]:
df = pd.read_csv('learn.csv')
dataset = df.dropna()
x = dataset.iloc[:,0:10].values#independent
y = dataset.iloc[:,-1].values#dependent
#y1 = dataset.iloc[:,-1].values#dependent2
print(x[0])
print(y[0])
#print(y1[1])

['Student 1' 65 31 20 44 27 45 15 247 62.53164557]
Medium


In [49]:
#encoding independent
labelencoder_x = LabelEncoder()
x[:, 0] = labelencoder_x.fit_transform(x[:, 0])
print(x)
#print(np.unique(x[:,0]))

[[0 65 31 20 44 27 45 15 247 62.53164557]
 [11 50 51 32 50 27 39 21 270 68.35443038]
 [22 49 35 32 36 35 27 15 229 57.97468354]
 [33 39 39 38 38 23 33 11 221 55.94936709]
 [44 47 43 44 54 45 25 19 277 70.12658228]
 [46 73 43 32 50 35 43 19 295 74.6835443]
 [47 53 37 30 38 33 33 17 241 61.01265823]
 [48 55 39 26 48 43 37 21 269 68.10126582]
 [49 31 53 38 22 21 23 15 203 51.39240506]
 [1 55 37 38 46 27 25 21 249 63.03797468]
 [2 51 53 34 44 41 23 13 259 65.56962025]
 [3 49 49 36 36 19 14 13 216 54.6835443]
 [4 29 43 20 18 17 15 11 153 38.73417722]
 [5 41 42 26 42 33 21 11 216 54.6835443]
 [6 23 33 14 22 15 15 5 127 32.15189873]
 [7 65 31 20 44 27 21 15 223 56.4556962]
 [8 26 35 20 20 21 17 11 150 37.97468354]
 [9 45 45 30 42 33 15 5 215 54.43037975]
 [10 48 45 30 23 33 29 13 221 55.94936709]
 [12 41 47 24 50 29 31 11 233 58.98734177]
 [13 39 35 32 42 32 20 15 215 54.43037975]
 [14 53 39 29 24 25 33 27 230 58.2278481]
 [15 43 47 32 38 33 34 29 256 64.81012658]
 [16 45 49 30 42 40 29 11 24

In [50]:
#dummyencoding
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse=False), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x[0])


[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 65 31 20 44 27 45
 15 247 62.53164557]


C:\Users\Dell\AppData\Roaming\Python\Python39\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [51]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print(y)

[2 0 2 2 1 2 2 0 1 0 0 2 2 2 1 2 2 2 2 2 2 2 0 2 1 1 1 0 2 0 0 0 0 1 2 1 0
 1 1 1 1 1 2 1 0 2 2 1 0 1]


In [52]:
#dependent1
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)
print(x_train)

[[0.0 0.0 0.0 ... 21 311 78.73417722]
 [0.0 0.0 0.0 ... 7 124 31.39240506]
 [0.0 0.0 0.0 ... 27 230 58.2278481]
 ...
 [0.0 0.0 0.0 ... 11 153 38.73417722]
 [0.0 0.0 0.0 ... 9 133 33.67088608]
 [0.0 0.0 0.0 ... 21 285 72.15189873]]


In [53]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 53 49 32 42 41
  37 15 269 68.10126582]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 18 24 18 18 15
  17 9 119 30.12658228]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 15 29 14 19 11
  9 8 105 26.58227848]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 21 43 16 15 19
  13 9 136 34.43037975]
 [0.0 0.0 0.0 0.0 0.

In [54]:
print(y_train)

[0 1 2 0 2 2 1 1 0 2 1 2 2 1 2 1 1 1 0 0 2 0 2 2 2 1 2 0 1 0 2 2 2 2 2 0 1
 2 1 1]


In [55]:
print(y_test)

[0 1 1 1 2 2 0 0 2 0]


In [56]:
sc = StandardScaler()
x_train_standard = sc.fit_transform(x_train)
x_test_standard = sc.transform(x_test)
print(x_test_standard[0])

[-0.16012815 -0.16012815 -0.16012815 -0.16012815 -0.16012815 -0.16012815
 -0.16012815 -0.16012815 -0.16012815 -0.16012815 -0.16012815 -0.16012815
 -0.16012815 -0.16012815 -0.16012815 -0.16012815 -0.16012815 -0.16012815
 -0.16012815 -0.16012815  1.         -0.16012815  0.          0.
 -0.16012815  0.         -0.16012815 -0.16012815 -0.16012815  0.
 -0.16012815 -0.16012815  0.          0.         -0.16012815  0.
 -0.16012815 -0.16012815 -0.16012815 -0.16012815 -0.16012815  0.
 -0.16012815  0.         -0.16012815 -0.16012815 -0.16012815 -0.16012815
 -0.16012815 -0.16012815  0.71272469  0.89075833  0.59450522  0.4125384
  1.2759795   1.33415714  0.09975709  0.92966812  0.92966812]


In [57]:
print(x_train_standard)

[[-0.16012815 -0.16012815 -0.16012815 ...  1.18801621  1.63606452
   1.63606452]
 [-0.16012815 -0.16012815 -0.16012815 ... -1.35125508 -1.50908136
  -1.50908136]
 [-0.16012815 -0.16012815 -0.16012815 ...  2.27627533  0.2737286
   0.2737286 ]
 ...
 [-0.16012815 -0.16012815 -0.16012815 ... -0.625749   -1.02133146
  -1.02133146]
 [-0.16012815 -0.16012815 -0.16012815 ... -0.98850204 -1.3577107
  -1.3577107 ]
 [-0.16012815 -0.16012815 -0.16012815 ...  1.18801621  1.19877151
   1.19877151]]


Decisiontreeclassifier

In [58]:
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.model_selection import GridSearchCV
import matplotlib.pyplot as plt

param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [3, 5, 7, 9],
    'min_samples_split': [2, 4, 6, 8],
    'min_samples_leaf': [1, 2, 3, 4]
}
model = DecisionTreeClassifier()
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5)
grid_search.fit(x_train_standard, y_train)
print("Best hyperparameters:", grid_search.best_params_)
best_dtc = DecisionTreeClassifier(**grid_search.best_params_)
best_dtc.fit(x_train_standard, y_train)


Best hyperparameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_leaf': 3, 'min_samples_split': 8}


DecisionTreeClassifier(max_depth=7, min_samples_leaf=3, min_samples_split=8)

In [59]:
from sklearn.metrics import accuracy_score,precision_score,f1_score,recall_score
print(best_dtc.score(x_test_standard,y_test))


0.8


In [60]:
f = best_dtc.predict([x_test_standard[5,:]])
print("Predicted:\t")
if (f==0):
    print("DIFFICULT")
if (f==1):
    print("EASY")
if (f==2):
    print("MEDIUM")


Predicted:	
MEDIUM


In [61]:
d= (y_test[5])
if (d==0):
    print("DIFFICULT")
if (d==1):
    print("EASY")
if (d==2):
    print("MEDIUM")

MEDIUM


logisticregression

In [62]:
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
model1.fit(x_train_standard,y_train)
model1.predict(x_test_standard)

array([2, 1, 1, 2, 2, 2, 2, 2, 2, 2])

In [63]:
from sklearn.metrics import accuracy_score
print(model1.score(x_test_standard,y_test))


0.5


In [64]:
f = model1.predict([x_test_standard[5,:]])
print("Predicted:\t")
if (f==0):
    print("DIFFICULT")
if (f==1):
    print("EASY")
if (f==2):
    print("MEDIUM")


Predicted:	
MEDIUM


In [65]:
d= (y_test[5])
if (d==0):
    print("DIFFICULT")
if (d==1):
    print("EASY")
if (d==2):
    print("MEDIUM")

MEDIUM


NEURAL NETWORK(MLP)

In [66]:
from sklearn.neural_network import MLPClassifier
model3 = MLPClassifier()
model3.fit(x_train_standard,y_train)
model3.predict(x_test_standard)


array([0, 1, 1, 2, 0, 0, 1, 0, 1, 0])

In [67]:
from sklearn.metrics import accuracy_score
print(model3.score(x_test_standard,y_test))

0.5


In [68]:
f = model3.predict([x_test_standard[7,:]])
print(f)
print("Predicted:\t")
if (f==0):
    print("DIFFICULT")
if (f==1):
    print("EASY")
if (f==2):
    print("MEDIUM")


[0]
Predicted:	
DIFFICULT


In [69]:
d= (y_test[7])
print(d)
if (d==0):
    print("DIFFICULT")
if (d==1):
    print("EASY")
if (d==2):
    print("MEDIUM")

0
DIFFICULT


RANDOMFOREST

In [70]:
from sklearn.ensemble import RandomForestClassifier
model4 = RandomForestClassifier()
model4.fit(x_train_standard,y_train)
model4.predict(x_test_standard)

array([0, 1, 1, 1, 2, 2, 2, 0, 2, 0])

In [71]:
from sklearn.metrics import accuracy_score
print(model4.score(x_test_standard,y_test))


0.9


In [72]:
f = model4.predict([x_test_standard[7,:]])
print(f)
print("Predicted:\t")
if (f==0):
    print("DIFFICULT")
if (f==1):
    print("EASY")
if (f==2):
    print("MEDIUM")


[0]
Predicted:	
DIFFICULT


In [73]:
d= (y_test[7])
print(d)
if (d==0):
    print("DIFFICULT")
if (d==1):
    print("EASY")
if (d==2):
    print("MEDIUM")

0
DIFFICULT


In [74]:
from sklearn import svm
svmclf = svm.SVC()
svmclf.fit(x_train_standard, y_train)
svmclf.predict(x_test_standard)
from sklearn.metrics import accuracy_score
print(svmclf.score(x_test_standard,y_test))

0.5


In [75]:
f = svmclf.predict([x_test_standard[8,:]])
print(f)
print("Predicted:\t")
if (f==0):
    print("DIFFICULT")
if (f==1):
    print("EASY")
if (f==2):
    print("MEDIUM")


[2]
Predicted:	
MEDIUM


In [76]:
d= (y_test[8])
print(d)
if (d==0):
    print("DIFFICULT")
if (d==1):
    print("EASY")
if (d==2):
    print("MEDIUM")

2
MEDIUM
